FLASK_ENV=development
FLASK_APP=app:create_app
FLASK_RUN_HOST=0.0.0.0
FLASK_RUN_PORT=5001
SECRET_KEY=CBnawGFQMiFH0fO8G2rML8kizDPy9zlY_FJbLQyRBFA
URL_EXTERNAL_STOCK=https://stooq.com/q/l/?f=sd2t2ohlcvn&h&e=json&s={}

RABBITMQ_HOST=127.0.0.1
RABBITMQ_PORT=5672
RABBITMQ_VHOST=/
RABBITMQ_USER=guest
RABBITMQ_PWD=guest
RABBITMQ_EXCHANGE=jobsity
RABBITMQ_EXCHANGE_TYPE=direct
RABBITMQ_QUEUE_STOCK=stock_service
RABBITMQ_QUEUE_API=api_service
